### PR TITLE
4.7 what-is-civievent

### PR DESCRIPTION
**Pull request by ziako**

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
@bgm @ziako - looks like you have open this pr on the wrong repo - should be on fr?

**Comment by ziako** [comment]
ok this is a mistake,  I'm new to github for translation. Can you remove?

**Comment by michaelmcandrew** [comment]
@ziako - no problem - am closing the request...

**Comment by ziako** [comment]
Thank you
best regards

**Comment by michaelmcandrew** [comment]
@ziako - sure. just give me a shout if you ever want to talk about translation of documentation some more...

**Comment by ziako** [comment]
hi, I have free time and I intend to continue the translation. I also translated "create an event" and "Planning and Management".  I will wish to integrate screenshot in French but I am not allowed

**Comment by michaelmcandrew** [comment]
>  I will wish to integrate screenshot in French but I am not allowed

can you expand on that? have you seen this repo? https://github.com/civicrm-french/civicrm-user-guide

**Comment by ziako** [comment]
Yes I work on this repo CiviCRM-french / CiviCRM-user-guide. If I try to upload files to / img: he said: "Downloads are disabled .... The file downloads require a push access to the repository "... how to import screenshots? the tab create a file? I'll try it

**Comment by michaelmcandrew** [comment]
@ziako - your other option (which might make more sense if you are doing ongoing work on the repo is to fork it, make the changes on your fork and then create pull requests. @bgm might have more info on how things are working on the french repo...

**Comment by ziako** [comment]
I created a personal fork and that's ok. I can download an screenshot. I will do a PR on the French repo.
thanks for your help

**Comment by michaelmcandrew** [comment]
Great - give me a shout if you have any other issues :)

**Comment by ziako** [comment]
thanks, but not at the moment. I will integrate the screenshot on the page, do a PR and see the result.

**Pull request closed without merging**
