### PR TITLE
clear up vague with specifics

### PR DESCRIPTION
**Pull request by Stoob**
Vague and inaccurate description of how data changed tracked.

### CODE REVIEW

**Review by MegaphoneJon — CHANGES_REQUESTED** [review]
I think there's a problem with the docs in that "Detailed Logging" is conflated with "available from the Change Log tab".  Most of these changes are true for the tab but not logging as a whole, so I'm not sure this is more correct.

The "Change Log" tab provides access to the "Contact Logging Report (Summary)" report, for which your changes are true.  However, all data changes ARE logged (e.g. updates to Contributions), just unavailable from that report.  Extended Reports has a Contribution Logging report, and direct SQL access to the logs is a feature in itself.  I also have an extension that uses logs to display changes to an activity status (as a means of tracking a workflow).

If we could have a short overview of detailed logging (which I think we could do by leaving lines 17-32 alone), then say, "Detailed logging allows changes the Change Log tab" and accept your changes on lines 34 down (and optionally shift info added to line 32 down there) it would be correct.

**Comment by Stoob** [comment]
I didn't even realize the Contact Logging Report (Summary) existed.  My problem with the documentation is that it implies greater change logging for *all* data than is actually available.  For example: the compare and revert features of the "Update" entries apply only to Contacts.  

If someone were to edit an existing Contribution, then save, this shows up as an Insert/Delete and there is no way to compare the data, much less revert it.  In the attached, Francisco edited the contribution, this is how it looks, and I cannot see what his edit was (without restoring from a backup).  

How does this work into your proposal?

compare

**Comment by MegaphoneJon** [comment]
First - the "Contact Logging Report (Summary)" IS the change log tab.  "Contact Logging Report (Detail)" is the screen you get when you click to view a change.

Second - it's not my experience that you can't view updates to contributions.  I see your screenshot, but I'll raise you mine.  I changed an existing contribution from $13 to $16.  Note that I have Line Item Editor and Summary Fields installed, so you see changes to those as well:
Selection_908

Selection_909

**Comment by Stoob** [comment]
I wish I saw that, but not on my install.  I just see Insert/Delete. Whelp, not sure what to offer at this point.  :-) I'm hoping that the documentation isn't inaccurate and doesn't make false promises but I'll withdraw my PR due to lack of knowledge of how the feature works (or doesn't).  Please close and/or delete @MegaphoneJon

**Pull request closed without merging**
