### PR TITLE
Convert JPEG & GIF images to PNG

### PR DESCRIPTION
**Pull request by aydun**
For JPEG & GIF files:
 - convert filenames with spaces to underscores
 - make path absolute
 - convert to PNG format

### CODE REVIEW

**Comment by aydun** [comment]
Done in two phases for clearer commits:

1) convert filename with spaces to underscores, lowercase extension:
script1.pl:
```
  if (/\!.*\/img\/(.*%20.*\.(png|jpg|jpeg|gif))/i) {
   $encoded_file = $1;
   $decoded_file = $encoded_file =~ s/%20/ /gr;
   $new_file = $decoded_file =~ s/ /_/gr;
   $new_file =~ s/(PNG|JPG|JPEG|GIF)$/lc($1)/e;
   s/$encoded_file/$new_file/;
   system("git mv 'img/$decoded_file' 'img/$new_file'");
  }
```
2) convert jpg/gif to png; make path absolute
script2.pl
```
  if (/\!.*\/img\/(.*\.(jpeg|jpg|gif))/) {
   $old_file = $1; 
   s/(\!.*)\.\.(\/img\/.*)/$1$2/;
   $new_file = $old_file =~ s/(jpeg|jpg|gif)$/png/r;
   s/$old_file/$new_file/;
   system("mogrify -format png 'img/$old_file' -path 'img/$new_file'");
   system("git rm 'img/$old_file'");
   system("git add 'img/$new_file'");
  }
```
as previously:
```
cd docs;
find . -name \*.md | xargs perl -pi ../script1.pl
find . -name \*.md | xargs perl -pi ../script2.pl
```
~

**Comment by seancolsen** [comment]
@aydun here are some thoughts: 

* Re-running this script seems like the best way forward (instead of rebasing)
* Being that we need to re-run it anyway, I think I'd rather keep the jpg and gif files. Here's why: 
    * png is preferable because it's lossless, so the image quality is higher. But if we get to png by first going through jpg or gif, then there is no advantage, since the lossy step has already been performed. 
    * One (very minor) upside of merging is that it makes things more consistent.
    * The (very minor) downside is that (I think) it increases the size of the repo because the old images are still stored in the history, along with the new ones too. I did a quick clone and then checkout of this branch and the repo size went from 60MB to 73MB. Not huge, sure. But it seems like it's just maybe not worth it, given that the only gain would be adding a small amount of consistency to things. 
    * I could be convinced though. Really not a big deal either way.
* So I'm thinking that perhaps the best way forward here would be to re-run the script in #290 but with gif and jpg included. 
* Note that in #328 I included jpg and gif

**Comment by xurizaemon** [comment]
There might be no improvement to existing jpeg images by converting to png, but it might help some future contributor see consistent png usage and follow form.

It's possible git just hasn't done its garbage collection after the clone above? If so, repo size might not be that bad down the line.

13MB does seem like a lot - maybe some [`mogrify -define png:foo`](http://www.imagemagick.org/script/command-line-options.php#define) settings to enable compression or (simpler) a `pngcrush` step can help. I do get where you're coming from with the larger repo size Sean!

If mkdocs supports build tasks, we could handle a lot of that there - reducing PNG size, any lint or link checking etc, notifying about any preferred format, whatever.

**Comment by aydun** [comment]
@seanmadsen - thanks for the thoughts
@xurizaemon - good idea on pngcrush

I've tried pngcrush on the converted images but it makes little difference: the files from mogrify total 7154KB, and after pngcrush (-brute): 6854KB.

However, there are 3 photos so if we leave those as JPEG's, the crushed total is 6005KB

Personally, I'm not overly concerned about the repo size compared to consistency.

Several of the screenshots would benefit from updating, so an alternative approach could be to add an issue to work through the JPEG screenshots and update them with fresh PNGs rather than converted ones.   That could be a fairly easy starter's task.

Let me know what you want to do & I'll prepare a PR to wrap up this bit.

**Comment by seancolsen** [comment]
Okay I'm on board with the thinking, generally that "consistency is preferable to small repo size", because look what I just noticed: 

* One person making image paths absolute: https://github.com/aydun/civicrm-user-guide/commit/2987f771bd19b4b5214298a937056a8bc893f1c6
* Another person making image paths relative: https://github.com/agh1/civicrm-user-guide/commit/ab1348fffb7a27b93959263fdcbc39dc6d768815

So @aydun how about you re-run this script as-is (with the logic to convert all images to PNG) and create a new PR?

**Comment by xurizaemon** [comment]
Build scripts might be a big ask, but style (PNG vs *, relative vs absolute) is the first step.

Does relative work better when viewing .md on GitHub vs docs.civicrm.org? (Would think the absolute would break on latter too since there's a `/user/en/latest` prefix.)

**Comment by seancolsen** [comment]
> Does relative work better when viewing .md on GitHub vs docs.civicrm.org?

Oh! Good point! You're right, @xurizaemon, relative links *do* work better on GH and absolute links don't work at all. I just tested. This is a bit of a bummer. 

To learn more about the decision to use absolute links, see: https://github.com/civicrm/civicrm-dev-docs/pull/204

I'm open to re-evaluating this decision. As I said in that PR linked above, I was originally looking for more feedback. This is the sort of decision that we can now bring up at a Working Group Meeting, but we didn't have those meetings back then. 

One way forward that allow us to reap the benefits of absolute URLs *and* still allow browsing on GitHub would be to set the [`docs_dir`](http://www.mkdocs.org/user-guide/configuration/#docs_dir) variable to `/` in `mkdocs.yml` and then move everything from the `docs` folder up one level. Or keep content in `docs` and begin all URLs with `/docs`. I'm 98% sure this would work. 

It any you want to advocate for taking a closer look at this stuff, maybe we can open a new ticket dedicated to making a decision about this and/or add this topic to the [meeting agenda](https://lab.civicrm.org/documentation/docs/tree/master/meetings#agenda-items)

**Comment by seancolsen** [comment]
Ok I've looked over this again and feel good about moving forward. I skimmed over all the changes and they look good. 

Thanks for all the work on this @aydun and thanks @xurizaemon for the thoughts!

**Pull request merged**
