### PR TITLE
Clarify rebuild groups jobs

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by francescbassas** [comment]
Thanks @eileenmcnaughton. Very useful.

As @michaelmcandrew asks here https://civicrm.stackexchange.com/q/31303/104 maybe it would be missing to document _Administer > Customize Data and Screens > Search Preferences 'Smart group cache timeout' setting_. I personally continue without being completely clear what is its purpose.

**Comment by eileenmcnaughton** [comment]
@francescbassas so if I create a group now then that group is valid for 5 minutes (if that is the timeout). If I seek to use it again within 5 minutes it will return the (slightly old) results. After 5 minutes any job that seeks to use the cache will flush it first - or the cleanup job will flush it.

Editing a contact will also flush any expired caches - there is a setting that can suppress that - but you need to flush by job for that - there is a bit more about that here https://civicrm.org/blog/eileen/478-group-contact-cache-deadlocks-improvement

**Comment by homotechsual** [comment]
@eileenmcnaughton do you feel docs changes are needed in response to @francescbassas or can this be merged?

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO that could be another issue perhaps?

**Comment by homotechsual** [comment]
Ok - new issue opened #399 

Happy for me to merge this?

**Comment by eileenmcnaughton** [comment]
yep

**Pull request merged**
