### PR TITLE
Remove Resource URLs page

### LINKED ISSUE #398: Resource URL documentation is confusing and not updated for changes in 4.7+
Docs page: https://docs.civicrm.org/user/en/latest/initial-set-up/resource-urls/

GL issue: https://lab.civicrm.org/documentation/docs/issues/8

As per the GL issue from @totten this page still appears to be out of date and requires some TLC.

### PR DESCRIPTION
**Pull request by homotechsual**
This content is well covered in SysAdmin and Dev guides and isn't really "user facing" information.

### CODE REVIEW

**Comment by homotechsual** [comment]
@totten I'd appreciate your thoughts on this.

**Comment by demeritcowboy** [comment]
I didn't see much in the sysadmin or dev guide about resource url but agree it's not end-user information and is outdated. The only currently useful part I see is about cleanup caches and paths which is in the sysadmin guide.

Related: https://lab.civicrm.org/dev/core/-/issues/1647 - there are technically multiple resource urls now, and some things might be changing.

**Comment by aydun** [comment]
Much of that 'Initial set-up' section is not going to be done by your average user - which is part of a bigger issue: we could do better at signposting 'everyday users' from 'administrators' to find relevant content.  The distinction between the 'user' and 'system administrator' guides works, but 'user' covers a broad spectrum combining 'everyday users' and 'administrators'.

Some of the smaller sections (eg Reporting, Campaigns, Survey etc) have 'Set-up' and 'Everyday tasks' sections that help guide readers to the right content.  

Larger sections (eg Membership, Events) don't have those sections and bundle together setup/admin things with everyday tasks.

If we want to cover all the administrator functions within the user guide maybe we can expand the 'Set-up' vs 'Everyday tasks' pattern.  

Going back to your original question, that resource url's page does not add much and I agree it can go.

**Comment by homotechsual** [comment]
I'm keen to open a conversation about a radical restructure of documentation. 

I'm planning to explore this by separating all setup/installation information into a separate guide. I'd like to see if a move towards that "style" of organising documentation works.

**Pull request merged**
