### PR TITLE
Update is-civicrm-for-you.md

### PR DESCRIPTION
**Pull request by seancolsen**
Referring to StackExchange (as opposed to old CiviCRM forums) for help

---

These changes are not from me &mdash; they're from @marsh-circle who [posted](https://chat.civicrm.org/civicrm/pl/9iq3xppouty1pdn1y1aduttr3y) this diff in Mattermost

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
looks good - one thought 

> Forums are staffed mainly by volunteers

might be better as

> Stack Exchange questions are answered by volunteers

**Comment by seancolsen** [comment]
Thanks for the feedback, @michaelmcandrew I made that change in db8325952ff332dd797f1c4b9971d65880ef4a6f

**Comment by seancolsen** [comment]
Thanks for this improvement @marsh-circle!

**Comment by MarshCastle** [comment]
More than welcome - hope I can do loads more! :)

**Pull request merged**
