### PR TITLE
dev/event#6 Events 'same email' can be used to allow duplicate registrations

### PR DESCRIPTION
**Pull request by mlutfy**
Documents this change: https://lab.civicrm.org/dev/event/issues/6

### CODE REVIEW

**Review by homotechsual — APPROVED** [review]
Changes look good.

**Comment by homotechsual** [comment]
@mlutfy - merge with release of 5.17 on this or merge now?

**Comment by mlutfy** [comment]
Good point, might be better to wait.

**Comment by homotechsual** [comment]
Approved for merge with the release of 5.17

**Comment by seamuslee001** [comment]
5.17 has been out for a bit now so merging

**Pull request merged**
