### PR TITLE
Remove content moved to Sysadmin Guide

### PR DESCRIPTION
**Pull request by seancolsen**
After looking at #265 I went looking for other instances of the same thing and found this one.

I moved this content to the Sysadmin Guide a while back and forgot to delete it from the User Guide. Whoops! 

Proof that we're not loosing anything: https://docs.civicrm.org/sysadmin/en/latest/setup/#civicrm-system-status

### CODE REVIEW

**Comment by seamuslee001** [comment]
@seanmadsen I agree with the removal just wondering if we should reference the sysadmin content from somewhere maybe in the initial setup like if you see errors in the system status get your sysadmin to read over <x> about the issues?

**Comment by seancolsen** [comment]
@seamuslee001 I've looked for a place in the User Guide where it would feel natural to refer readers to the System Status section within the Sysadmin Guide, but I wasn't able to quickly identify such a place. If you want to suggest such a place, I'm happy to add edits to this PR. But otherwise, I think we should move ahead as-is.

**Comment by seamuslee001** [comment]
@seanmadsen i'm thinking maybe somewhere like this https://github.com/civicrm/civicrm-user-guide/blob/master/docs/initial-set-up/installation-and-basic-set-up.md#configuration

**Comment by seancolsen** [comment]
Cool, I've added another commit. What do you think now, @seamuslee001 ?

**Comment by seamuslee001** [comment]
Excellent happy with this merging

**Pull request merged**
