### PR TITLE
Initial page add for url searching.

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
Preliminary page on url searching - I could do with some help on how to make this work - it might get quite
busy as I work on other screens / fix the ones I couldn't add as yet. Formatting is kinda missing

See https://github.com/civicrm/civicrm-dev-docs/issues/624

Also in my testing I just opened 
https://github.com/civicrm/civicrm-core/pull/15787

Other than that the following test OK on contribution search as urls - ie. high, low & relative variants

    'contribution_recur_start_date',
      'contribution_recur_next_sched_contribution_date',
      'contribution_recur_cancel_date',
      'contribution_recur_end_date',
      'contribution_recur_create_date',
      'contribution_recur_modified_date',
      'contribution_recur_failure_retry_date',

@seamuslee001 @MikeyMJCO @monishdeb @lcdservices

### CODE REVIEW

**Comment by seamuslee001** [comment]
Comment on wrong PR

**Comment by homotechsual** [comment]
Added some formatting changes - are we envisioning this expanded for Contribution searches, Contact searches etc?

**Comment by seamuslee001** [comment]
@MikeyMJCO yes, at the moment it has coverage for the Find Contributions and FInd Participants screens and also advanced search for those two sections in the advanced search. It would be anticipated that more fields are added as we convert them over to being built off the metadata. would be my expectation @eileenmcnaughton ?

**Comment by homotechsual** [comment]
Merging this as is for now - can be expanded in future PRs.

**Pull request merged**
