### PR TITLE
Changing path for contributions invoice templates

### PR DESCRIPTION
**Pull request by themak1985**
Originally said CiviCRM - I believe it meant to say Communications

### CODE REVIEW

**Review by homotechsual — APPROVED** [review]
Change looks good to me - I agree that this was probably meant from the beginning.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @totten @colemanw who has merge rights?

**Comment by homotechsual** [comment]
@MegaphoneJon (at the very least) has merge rights.

**Review by MegaphoneJon — APPROVED** [review]

**Comment by MegaphoneJon** [comment]
Thanks @themak1985!

**Pull request merged**
