### PR TITLE
Add asking-for-help-in-chat.md to Book.

### PR DESCRIPTION
**Pull request by homotechsual**

### CODE REVIEW

**Review by MegaphoneJon — COMMENTED** [review]
I can see the page this links to in master - but it's a 404 on the docs site. I thought we had fixed the mkdocs publishing script?  Do you know what's up @MikeyMJCO?  I don't want to merge a bad link.

**Comment by homotechsual** [comment]
Because it's not in the YML I don't think it's "routable".

**Comment by homotechsual** [comment]
When I update the mkdocs.yml in dev and update the book it works fine on my docs-publisher-dev

**Comment by MegaphoneJon** [comment]
Works for me.  Thanks @MikeyMJCO !

**Comment by homotechsual** [comment]
Just for completeness: https://docs.civicrm.org/user/en/latest/the-civicrm-community/asking-for-help-in-chat/

**Comment by homotechsual** [comment]
Thanks @MegaphoneJon for all the commits :-) I may "take over" some of the other PR's if the original authors don't come back to them just in the interests of clearing the PR queue and getting the docs in even better shape!

**Pull request merged**
