### PR TITLE
WIP - Core scheduled jobs

### PR DESCRIPTION
**Pull request by xurizaemon**
A first stab at generating docs from JS.

Doesn't have to be JS of course, just exploring ...

via https://gist.github.com/xurizaemon/e66ed3d0127907284728ef79be57363c

### CODE REVIEW

**Comment by xurizaemon** [comment]
WIP for now. Mostly filed this just to illustrate some thoughts about having [some docs info be automatically generated](https://gist.github.com/xurizaemon/e66ed3d0127907284728ef79be57363c).

* Are there better / existing tools we could use for this?
* Where should docs generators live (this repo, this branch, elsewhere?)
* What should they be written in?

etc

**Comment by seancolsen** [comment]
@xurizaemon do you have thoughts about next steps here? Would you like to see this merged? Is there more work you have planned on this front? I think it's a cool idea! (I don't really have opinions/answers to the questions you raise and am happy to follow your lead on this project.)

**Comment by xurizaemon** [comment]
*struggles to recall writing the linked code*

Ehhh ... now I'm wishing I'd documented the way to regenerate the linked docs. I don't see any reason why the changes here can't be committed though!

**Comment by seancolsen** [comment]
I think if we merge this as-is we'll basically need to consider it to be something like "script-assisted docs starting point" (not "auto-generated docs"). What I mean is: this would be like a one-time push to use auto-docs as a starting point for docs that would be manually maintained thereafter. If we merge these changes and do nothing else, I think it's going to be difficult to re-run your script a year from now. I'm fine with this, but just want to check with you that *you're* fine with this. 

On the other hand, if we wanted to aim for truly auto-generated docs for this content we'd do the following: 

1. put your script in this repo
1. document the process of re-running your script
1. make it clear which content has been auto-generated and put warnings (perhaps in HTML comments) to prevent content editors from manually editing the content that has been auto-generated

I'm not arguing that we should go that route, just wanting to acknowledge that if we merge now we're potentially abandoning that route. Is the "script-assisted docs starting point" okay with you @xurizaemon ? If so, I'll merge now.

**Comment by xurizaemon** [comment]
Help me understand why you think it would be difficult to run the script in future? Some stabs I might take 🗡 

- The output won't merge cleanly because it doesn't fit. (It outputs to a separate file so should be clean landing?)
- The output won't merge cleanly because people have patched that newly added doc. (Good point.)
- The script will be forgotten / undocumented. (Happy to document this!)

**Comment by seancolsen** [comment]
Yes, I was thinking of your last 2 points.

**Comment by xurizaemon** [comment]
Some docs then to show how this example can be used 😁 

* [These two files](https://gist.github.com/xurizaemon/e66ed3d0127907284728ef79be57363c) can live in eg `~/Documents/civicrm-docs/scripts/scheduled-jobs`
* `cd ~/Documents/civicrm-docs/scripts/scheduled-jobs && npm install` (now the dependencies are installed)
* `cd ~/Sites/civicrm.dev` (now you're in a working CiviCRM site)
* `node ~/Documents/civicrm-docs/scripts/scheduled-jobs/main.js` (run main.js while you're in the site, so `cv` can bootstrap site for API)
* Will output .md which you can use to update the page [as shown in the PR](https://github.com/civicrm/civicrm-user-guide/pull/148)

Paths above are not significant, except to demonstrate that the docs repo and the civi site used to generate are decoupled and you only need a `cv`-capable CiviCRM install to update the docs.

Output is as below.

Ideally people would NOT patch `scheduled-jobs.md` except by modifying the job definitions in CiviCRM. Probably we need a marker to say "this file is autogenerated, edit it either here (link to `main.js`) or here (link to scheduled job definitions)."

**Comment by xurizaemon** [comment]
# Core jobs

Below is a table of common jobs which might appear on a CiviCRM install. Extensions can add their own jobs - jobs for your site are in CiviCRM under **Administer > System Settings > Scheduled Jobs**.

name | entity.action | run_frequency | description
--- | --- | --- | ---
CiviCRM Update Check | job.version_check | Daily | Checks for CiviCRM version updates. Important for keeping the database secure. Also sends anonymous usage statistics to civicrm.org to to assist in prioritizing ongoing development efforts.
Send Scheduled Mailings | job.process_mailing | Always | Sends out scheduled CiviMail mailings
Fetch Bounces | job.fetch_bounces | Hourly | Fetches bounces from mailings and writes them to mailing statistics
Process Inbound Emails | job.fetch_activities | Hourly | Inserts activity for a contact or a case by retrieving inbound emails from a mail directory
Process Pledges | job.process_pledge | Daily | Updates pledge records and sends out reminders
Geocode and Parse Addresses | job.geocode | Daily | Retrieves geocodes (lat and long) and / or parses street addresses (populates street number, street name, etc.)
Update Greetings and Addressees | job.update_greeting | Daily | Goes through contact records and updates email and postal greetings, or addressee value
Mail Reports | job.mail_report | Daily | Generates and sends out reports via email
Send Scheduled Reminders | job.send_reminder | Daily | Sends out scheduled reminders via email
Update Participant Statuses | job.process_participant | Always | Updates pending event participant statuses based on time
Update Membership Statuses | job.process_membership | Daily | Updates membership statuses. WARNING: Membership renewal reminders have been migrated to the Schedule Reminders functionality, which supports multiple renewal reminders.
Process Survey Respondents | job.process_respondent | Always | Releases reserved survey respondents when they have been reserved for longer than the Release Frequency days specified for that survey.
Clean-up Temporary Data and Files | job.cleanup | Hourly | Removes temporary data and files, and clears old data from cache tables. Recommend running this job every hour to help prevent database and file system bloat.
Send Scheduled SMS | job.process_sms | Always | Sends out scheduled SMS
Rebuild Smart Group Cache | job.group_rebuild | Always | Rebuilds the smart group cache.
Disable expired relationships | job.disable_expired_relationships | Daily | Disables relationships that have expired (ie. those relationships whose end date is in the past).
Validate Email Address from Mailings. | mailing.update_email_resetdate | Daily | Updates the reset_date on an email address to indicate that there was a valid delivery to this email address.

**Comment by seancolsen** [comment]
@xurizaemon As I think you've probably seen by now, I recently did some extensive re-write work on the scheduled jobs content after creating the Sysadmin Guide. It's now split into two pages: 

* https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/
    * Targets users 
    * describes the Scheduled Jobs within the UI
    * (new) aims to comprehensively describe [each job](https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/#specific-jobs), including the parameters available
* https://docs.civicrm.org/sysadmin/en/latest/setup/jobs/
    * Targets system administrators
    * describes how to set up your cron job to call `Job.execute` and make your scheduled jobs run automatically

The content generated by your script seems to have similar goals as the [specific jobs](https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/#specific-jobs) section of the new page. When I wrote that content I definitely thought about this auto-generated content from you. I even considered finding a way to incorporate your script. But in working on this content I formed the following opinions: 

* Documenting parameters in the User Guide is important. Why? Well, the UI sort of attempts to document parameters, but its approach is terrible IMHO. The only doc on parameters in the UI (that I could find) is the *default value* of the parameters field. So as soon as you actually set parameters you lose all the doc. Plus, I found many parameters in the code that were not documented in those default values. Users can delete scheduled jobs &mdash; another thing that leads to the loss of parameter docs. So I think we need to have these documented somewhere.
* It's hard to auto-generate docs that include parameters. This would be easier if all the actions had `_spec` functions. For example with `Job.geocode` there's [_civicrm_api3_job_geocode_spec](https://github.com/civicrm/civicrm-core/blob/03c5ceba7e09286479dcc37920387ef84d8c01ec/api/v3/Job.php#L141) which could theoretically be used to generate the parameters found in the [`Job.geocode`](https://docs.civicrm.org/user/en/latest/initial-set-up/scheduled-jobs/#job_geocode) docs I wrote. But most of the actions don't have a `_spec` function :slightly_frowning_face: 

**My proposal at this point is to close this PR** in favor of the docs which now exist, even though they must be manually maintained. What do you think @xurizaemon ?

**Comment by seancolsen** [comment]
I'll close this on December 1st if there are no further comments.

**Pull request closed without merging**
