### PR TITLE
Add URLs for WP, Backdrop to info about public group subscribe page

### PR DESCRIPTION
**Pull request by highfalutin**

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
@highfalutin could you please update the PR to reflect Clean URL support for WP in Civi 5.13+?  [Here is an example](https://civicrm.stackexchange.com/a/15932/12) of indicating this, though in this case it would be good to indicate something like "WordPress" and "WordPress without Clean URL support enabled".

**Comment by homotechsual** [comment]
@highfalutin sorry to put you on the hook for this but you've thrown into my spotlight a s[tyle-guide contravention](https://docs.civicrm.org/dev/en/latest/documentation/style-guide/#urls) :-)

Specifically:

> Sample links to specific CiviCRM URL paths should use example.org as the domain.

Could I ask you to widen the scope of your PR to change the URLS in that list to use example.org.

**Comment by homotechsual** [comment]
If you can't that's ok - I'll approve this one and then make those changes myself!

**Review by highfalutin — COMMENTED** [review]
@MikeyMJCO here you go!

**Review by homotechsual — APPROVED** [review]

**Comment by homotechsual** [comment]
Approved!

**Pull request merged**
