### PR TITLE
Adding reference to mapping languages to regional translations Issue#7

### PR DESCRIPTION
**Pull request by shaneonabike**
I have updated the documentation as per my request https://lab.civicrm.org/dev/translation/issues/7#note_3554 in order to provide further information to CiviCRM users with regards to mapping regional languages to the proper translations

### CODE REVIEW

**Comment by shaneonabike** [comment]
@mlutfy here's the patch that I had originally said that I would write up. Let me know if you have any tweaks in what has been written that you would like me to integrate.

**Comment by MegaphoneJon** [comment]
This information all looks correct.  However, it's my sense that this is the wrong place.  I know @mlutfy recommended it go here, so it'd be great if he chimed in.  However, this page seems to be about creating localizations, whereas this is about installing them.  It seems that the current best documentation for installing l10ns is the wiki page which you originally linked to - and is linked from the "install CiviCRM" docs.

I'm not sure what to do here.  It seems that short of migrating [the i18n wiki page](https://wiki.civicrm.org/confluence/display/CRMDOC/i18n+Administrator%27s+Guide%3A+Using+CiviCRM+in+your+own+language) to the docs, there's no place to put this information.  And I don't want to put that on you!  I'm interested in your thoughts @shaneonabike as well as Mathieu's.

Perhaps we open a ticket for migrating the wiki page?

**Comment by shaneonabike** [comment]
Most of that content is in the page that I updated... Although I did think it was kind of misplaced. To be honest this is the _only_ page that appears for localization or translation when searched. Therefore, maybe it's even easier for us to simply move the entire file to another section. Or break it apart to have a section in the original CiviCRM docs for installing, and another (with a reference) on contributing to the community.

@mlutfy thoughts?

**Comment by mlutfy** [comment]
That "localising civicrm" page has a lot of stuff, from CiviCRM configurations, to building translation teams on Transifex. I have to admit that the focus of the page should be "community" (which would invalidate 80% of the content of the page), but right now, it's all we have.

This topic (regional inherit) is particularly annoying, because it's an admin configuration, similar to setting a default language, but it is not exposed as a setting, making it a [sysadmin](https://docs.civicrm.org/sysadmin/en/latest/)-ish kind of doc?

Another important bit missing from the old wiki, is how to enable Native Gettext.

Some docs have been migrated here, but it's messy: https://lab.civicrm.org/dev/translation/wikis/home

That said, by lack of a better place, I would merge so that it's at least easier to discover, and restructure later?

**Comment by shaneonabike** [comment]
Sure! I agree that it's a mess also and would prefer that it's more community. Do you want me to open another bug related to the restructure?

**Comment by shaneonabike** [comment]
Also, I would imagine that you have the power of doing the merge right?

**Comment by shaneonabike** [comment]
Can we push this as I think it will help other users?

**Comment by MegaphoneJon** [comment]
Fair enough!

**Pull request merged**
