### PR TITLE
Make image paths absolute

### PR DESCRIPTION
**Pull request by aydun**

### CODE REVIEW

**Comment by aydun** [comment]
```
cd docs;
find . -name \*.md | xargs perl -pi -e 's/(\!.*)\.\.(\/img\/.*\.png)/$1$2/i;'
```

**Review by seancolsen — CHANGES_REQUESTED** [review]
@aydun This is great. Bu can you change `png` to `(png|jpg|gif)` and re-run to catch more?

**Comment by aydun** [comment]
I've done this as part of #295 for non png's

**Comment by seancolsen** [comment]
There were enough merge conflicts here that re-running the script was the quickest way forward, so I did that in #328

**Pull request closed without merging**
