### PR TITLE
Fix markdown difference between github and mkdocs

### PR DESCRIPTION
**Pull request by demeritcowboy**
I didn't realize the bullets markdown on github is different.
@MikeyMJCO

### CODE REVIEW

**Comment by homotechsual** [comment]
We don't use - markup for bullets. It needs to be * followed by two spaces please.

e.g: `*  some text`

**Comment by demeritcowboy** [comment]
Oh ok. I copied from lower down in the same file.

**Comment by homotechsual** [comment]
The other references to the - syntax will get fixed when we start linting docs :-)

**Comment by demeritcowboy** [comment]
Ok thanks!

**Comment by demeritcowboy** [comment]
Argh they're still squished.

**Comment by homotechsual** [comment]
They are? - Yes they are!

**Comment by demeritcowboy** [comment]
Yes and I'm trying to find an example with bullets and everything I see is dashes.

**Comment by homotechsual** [comment]
https://docs.civicrm.org/dev/en/latest/documentation/markdown/#lists

**Comment by demeritcowboy** [comment]
Hmm maybe just 1 space after the star then. Will try that.

**Comment by homotechsual** [comment]
For this use case however I think numbered lists would be better?

Syntax:

```markdown
1. List Item 1
1. List Item 2
```

E.g:

1. List Item 1
1. List Item 2

**Comment by homotechsual** [comment]
For bulleted lists however (if you wish!)

```markdown
*  Bullet 1
*  Bullet 2
```

E.g: 

*  Bullet 1
*  Bullet 2

**Comment by demeritcowboy** [comment]
ok

**Comment by homotechsual** [comment]
1 or 2 spaces should both work really.

**Comment by demeritcowboy** [comment]
Maybe it needs a blank line above the list. Will do that too.

**Comment by homotechsual** [comment]
Ah - yes it does. Sorry didn't spot that was missing!

**Pull request merged**
