### PR TITLE
Remove weird double dash character. Replace with single dash

### PR DESCRIPTION
**Pull request by jusfreeman**
I suspect this character has been copied from MS Word as it's giving weird non-printable output when viewing on a web page. Just replacing this with a single "normal" dash does the trick. This is a global find/replace.

### CODE REVIEW

**Comment by seancolsen** [comment]
That's an [em dash](https://en.wikipedia.org/wiki/Dash#Em_dash). It's a legitimate&mdash;and relatively commonly used&mdash;punctuation mark.

## Usage

Personally, I find it quite useful &mdash; though it's worth pointing out that different people use it in slightly [different ways](http://www.thepunctuationguide.com/em-dash.html). Our [style guide](https://docs.civicrm.org/dev/en/latest/documentation/style-guide/) does not specify how docs authors should use it.

In our docs, there are two ways to insert an em dash:

* Insert the [em dash Unicode character](http://www.fileformat.info/info/unicode/char/2014/index.htm), `—`, as is done in these cases you are proposing we change
* Insert the HTML entity, `&mdash;`, as is done [elsewhere](https://github.com/civicrm/civicrm-dev-docs/search?utf8=%E2%9C%93&q=%26mdash%3B&type=) in our documentation

## Display

Here is a screenshot of how the em dash is displaying for me here https://docs.civicrm.org/user/en/latest/email/set-up/#mailing-list-confirmation-workflow

mockup

@jusfreeman Are you seeing the same thing I'm seeing? 

* If not
    * I'd like to figure out how I can replicate what you're seeing.
    * I'd be curious if you also observe unexpected behavior when viewing a page that uses the em dash *HTML entity* instead of the Unicode character, for example in the first sentence in [this section](https://docs.civicrm.org/dev/en/latest/security/#inputs-and-outputs). If that looks okay to you, then we could change em dash Unicode characters to em dash HTML entities. 
* If so, I'd like to understand more about why you want to change these em dashes to hyphens.

I'm concerned about changing em dashes to hyphens because the two symbols carry different meanings.

**Comment by jusfreeman** [comment]
Thanks Sean. Here's a screenshot of what I see after running the markdown to html converter and then importing into confluence.

I have updated the PR to use mdash instead and also removed a few instances where it was being used.

Screenshot:
encoding

**Comment by seancolsen** [comment]
Ok cool. So I merged this because I think that using HTML entities instead of Unicode characters is definitely fine. 

But I just can't help digging a little deeper with some questions here...

@jusfreeman  You say:

> running the markdown to html converter and then importing into confluence.

Can you tell me more about this? What exactly are you doing? Any why? This is not a docs use-case that I've been aware of. It seems like non-ASCII characters have been giving you trouble with this use-case and you've addressed this trouble by changing the User Guide in some place. The changes are fine, but one of the reasons I bring this up is because I'm sure there are other non-ASCII characters in the User Guide, and other guides too. Another way to address this trouble would be to run the markdown content through a script that encodes Unicode characters to HTML entities. 

But I'm also just curious what you're doing because it's new to me.

**Comment by jusfreeman** [comment]
@seanmadsen hit me up on MM for a chat about it if your still interested :)

**Comment by jusfreeman** [comment]
Thanks for merging.

**Pull request merged**
