### PR TITLE
Update set-up.md

### PR DESCRIPTION
**Pull request by gah242s**
Clickatell has changed their layouts and a few of the questions.  A new image also needs to be taken and inserted.

### CODE REVIEW

**Comment by michaelmcandrew** [comment]
@gah242s - thanks for this! Did you want to add the image? Might be easiest for you to do so, if you have easy access to the screen, etc.  If not, could you add an issue so we don't loose track of it, and I'll merge this request.

**Comment by joannechester** [comment]
@michaelmcandrew We should merge this into the 4.6 branch also.

**Comment by michaelmcandrew** [comment]
OK - lets wait for @gah242s to get back to us. should be straightforward to cherry pick this commit to 4.6

**Comment by gah242s** [comment]
Hopefully this will fit the bill.
screen shot 2016-04-27 at 8 29 19 am

**Comment by michaelmcandrew** [comment]
thanks @gah242s - could you add it to the repo and update the image link, etc. so we can see what it'll look like in place?

thanks

**Comment by gah242s** [comment]
@michaelmcandrew , I wouldn't mind doing so, except that I can't seem to find where the repo is.  All the docs I keep finding are on the Wiki and talk about book.civicrm.org or floss or other old things.

**Comment by michaelmcandrew** [comment]
Hey @gah242s, by repo, I meant this repo here on github: https://github.com/civicrm/civicrm-user-guide.

We keep images in https://github.com/civicrm/civicrm-user-guide/tree/master/docs/img.

Here's an example of how they can be referenced in a chapter:

```
![image](../img/CiviCRM_SMS_adding-a-provider.png) 
```

**Comment by michaelmcandrew** [comment]
hey @gah242s - any update on this - would be great to get your pr merged.

**Comment by gah242s** [comment]
Wow!  Sorry, I must have missed the 5-10 message.  I had no idea this was still out there.  Unfortunately, I don't seem to have push privileges to the images directory to upload the attached image above.  Otherwise, it seemed simple enough.

**Comment by gah242s** [comment]
Hope I did this somewhat right.  However, I still didn't see how I could actually upload the .png to the images file.  I requested a new empty file be created.  Hoping I didn't break it worse.

https://github.com/civicrm/civicrm-user-guide/compare/master...gah242s:patch-3

**Comment by michaelmcandrew** [comment]
@gah242s - thanks - I'm going to merge this and then open another PR with the image uploaded and explain what I did there...

**Comment by michaelmcandrew** [comment]
@gah242s - I did it for you this time - thought I better see if I could do it myself first :) the pull request here. https://github.com/civicrm/civicrm-user-guide/pull/133/files

Are you doing your edits via the UI or via a local copy of the repo?

If you are doing them via the UI, one way of uploading a file is by going to the directory that you want to upload them to https://github.com/civicrm/civicrm-user-guide/tree/master/docs/img and then clicking the Upload files button, which should take you here: https://github.com/civicrm/civicrm-user-guide/upload/master/docs/img.

If you are doing them locally, it should be fairly self explanatory, but I can answer any questions you have if that would help.

Thanks for the contribution in any case :)

**Pull request merged**
